### PR TITLE
Migrate to Emscripten's native Bazel rules.

### PR DESCRIPTION
**Pull request by PiotrSikora**
Signed-off-by: Piotr Sikora <piotrsikora@google.com>

### CODE REVIEW

**Comment by PiotrSikora** [comment]
Envoy PR: https://github.com/envoyproxy/envoy/pull/19579.

**Comment by PiotrSikora** [comment]
@lambdai @kyessenov @douglas-reid FYI, as this is going to break the auto-update in Istio Proxy.

Most notably, the path to generated `.wasm` files changes (see Envoy PR: https://github.com/envoyproxy/envoy/pull/19579).

**Comment by PiotrSikora** [comment]
Hold for some fixes.

**Comment by PiotrSikora** [comment]
Splitting this into 2 parts: update to Emscripten v3.1.1 (#133) and migration to `@emsdk` toolchain (this PR), since the toolchain needs more work upstream to make it work for us.

**Review by bianpengyuan — APPROVED** [review]

**Comment by PiotrSikora** [comment]
This is on hold until https://github.com/emscripten-core/emsdk/issues/971 and https://github.com/emscripten-core/emsdk/issues/972 are fixed.

**Review by mathetake — APPROVED** [review]

**Comment by PiotrSikora** [comment]
Note: This breaks Proxy-Wasm plugins that use `abseil-cpp`. The old toolchain's transition used `--cpu=wasm32` (supported by `abseil-cpp`), but `@emsdk` toolchain's transition uses `--cpu=wasm` (not supported by `abseil-cpp`), and results in `-pthread` being added to `linkopts`, which `emcc` converts into WebAssemby threads proposal, which isn't enabled.

I've added support for `--cpu=wasm` in https://github.com/abseil/abseil-cpp/pull/1129, which fixes build of Proxy-Wasm plugins in Istio Proxy, but it requires either updating `abseil-cpp` past https://github.com/abseil/abseil-cpp/pull/1129 or cherry-picking it.

**Pull request merged**
