### PR TITLE
Beautify code snippets.

### PR DESCRIPTION
**Pull request by Xunzhuo**
make readme read friendly

### CODE REVIEW

**Comment by bianpengyuan** [comment]
@Xunzhuo Thanks for your contribution! Please sign your PR and make DCO happy. Thanks! https://github.com/proxy-wasm/proxy-wasm-cpp-sdk/pull/100/checks?check_run_id=2320395400

**Comment by Xunzhuo** [comment]
> @Xunzhuo Thanks for your contribution! Please sign your PR and make DCO happy. Thanks! https://github.com/proxy-wasm/proxy-wasm-cpp-sdk/pull/100/checks?check_run_id=2320395400

Sure Everything is OK now, please take a look~😀

**Review by bianpengyuan — APPROVED** [review]

**Comment by Xunzhuo** [comment]
@PiotrSikora Please take a look~ Thanks😀

**Comment by PiotrSikora** [comment]
@Xunzhuo While you're at it, could you add language identifiers to other code snippets? There are a few `bash` and `makefile` snippets that are missing them. Thanks!

**Comment by Xunzhuo** [comment]
@PiotrSikora Sure~ Everything is ok now~ Please take a look😊

**Review by PiotrSikora — APPROVED** [review]
Thanks!

**Pull request merged**
