### PR TITLE
Fix the CI.

### PR DESCRIPTION
**Pull request by martijneken**

### CODE REVIEW

**Review by PiotrSikora — COMMENTED** [review]
Could you change `ubuntu-latest` to `ubuntu-22.04` to avoid base image change silently breaking this in the future?

**Comment by martijneken** [comment]
> Could you change `ubuntu-latest` to `ubuntu-22.04` to avoid base image change silently breaking this in the future?

Done, PTAL.

**Comment by martijneken** [comment]
Can we auto-run testing workflows in this repo? Seems like proxy-wasm-cpp-host does that.

**Review by PiotrSikora — APPROVED** [review]
Thanks!

**Comment by PiotrSikora** [comment]
@mpwarres could you merge it? It looks that I don't have the permission to do that in this repo anymore.

**Comment by PiotrSikora** [comment]
> Can we auto-run testing workflows in this repo? Seems like proxy-wasm-cpp-host does that.

They are executed automatically, but only for people who contributed previously (this is a GitHub-wide policy to prevent abuse). Once this PR is merged, your other changes will trigger CI automatically.

**Pull request merged**
